insert into macro_region(name) values ('Noroeste');
insert into macro_region(name) values ('Norte');
insert into macro_region(name) values ('Oeste');
insert into macro_region(name) values ('Sudoeste');
insert into macro_region(name) values ('Sul');

insert into region (name, macro_region_id) values ('Apucarana', 2);
insert into region (name, macro_region_id) values ('Campo Mourão', 1);
insert into region (name, macro_region_id) values ('Cascavel', 3);
insert into region (name, macro_region_id) values ('Cianorte', 1);
insert into region (name, macro_region_id) values ('Cornélio Procópio', 2);
insert into region (name, macro_region_id) values ('Curitiba', 5);
insert into region (name, macro_region_id) values ('Dois Vizinhos', 4);
insert into region (name, macro_region_id) values ('Francisco Beltrão', 4);
insert into region (name, macro_region_id) values ('Guarapuava', 5);
insert into region (name, macro_region_id) values ('Irati', 5);
insert into region (name, macro_region_id) values ('Ivaiporã', 2);
insert into region (name, macro_region_id) values ('Laranjeiras do Sul', 3);
insert into region (name, macro_region_id) values ('Londrina', 2);
insert into region (name, macro_region_id) values ('Maringá', 1);
insert into region (name, macro_region_id) values ('Pato Branco', 4);
insert into region (name, macro_region_id) values ('Ponta Grossa', 5);
insert into region (name, macro_region_id) values ('Santo Antonio da Platina', 2);
insert into region (name, macro_region_id) values ('Toledo', 3);
insert into region (name, macro_region_id) values ('União da Vitória', 5);

insert into city (name, state) values ('Alvorada do Sul PR', 'PR');
insert into city (name, state) values ('Andirá - PR', 'PR');
insert into city (name, state) values ('Ângulo Pr', 'PR');
insert into city (name, state) values ('Arapongas', 'PR');
insert into city (name, state) values ('Arapoti', 'PR');
insert into city (name, state) values ('Araucária -  PR.', 'PR');
insert into city (name, state) values ('Assaí', 'PR');
insert into city (name, state) values ('Assis Chateaubriand', 'PR');
insert into city (name, state) values ('Astorga/ Pr', 'PR');
insert into city (name, state) values ('Barra do Jacaré', 'PR');
insert into city (name, state) values ('BEI ', 'PR');
insert into city (name, state) values ('Bela Vista da Caroba', 'PR');
insert into city (name, state) values ('Bela Vista do Paraíso -Pr', 'PR');
insert into city (name, state) values ('Bituruna', 'PR');
insert into city (name, state) values ('BOA ESPERANÇA', 'PR');
insert into city (name, state) values ('Boa Vista Da Aparecida', 'PR');
insert into city (name, state) values ('Cafeara', 'PR');
insert into city (name, state) values ('Cambará', 'PR');
insert into city (name, state) values ('Cambira', 'PR');
insert into city (name, state) values ('Campina da Lagoa', 'PR');
insert into city (name, state) values ('Campo Mourão', 'PR');
insert into city (name, state) values ('CANDIDO DE ABREU', 'PR');
insert into city (name, state) values ('Capanema', 'PR');
insert into city (name, state) values ('Cascavel', 'PR');
insert into city (name, state) values ('Chopinzinho', 'PR');
insert into city (name, state) values ('Clevelândia – PR', 'PR');
insert into city (name, state) values ('Corbélia', 'PR');
insert into city (name, state) values ('Cornélio Procópio', 'PR');
insert into city (name, state) values ('CORONEL VIVIDA', 'PR');
insert into city (name, state) values ('CRUZEIRO DO IGUAÇU', 'PR');
insert into city (name, state) values ('Cruzmaltina', 'PR');
insert into city (name, state) values ('DOIS VIZINHOS', 'PR');
insert into city (name, state) values ('Doutor Camargo-PR.', 'PR');
insert into city (name, state) values ('Enéas Marques ', 'PR');
insert into city (name, state) values ('Engenheiro Beltrão', 'PR');
insert into city (name, state) values ('Entre rios Do Oeste', 'PR');
insert into city (name, state) values ('Espigão Alto Iguaçu Pr', 'PR');
insert into city (name, state) values ('Farol', 'PR');
insert into city (name, state) values ('Faxinal', 'PR');
insert into city (name, state) values ('Floraí Pr', 'PR');
insert into city (name, state) values ('FLORESTA', 'PR');
insert into city (name, state) values ('Florestópolis', 'PR');
insert into city (name, state) values ('Formosa do Oeste', 'PR');
insert into city (name, state) values ('Francisco Beltrao', 'PR');
insert into city (name, state) values ('Goioerê', 'PR');
insert into city (name, state) values ('Goioxim – Pr', 'PR');
insert into city (name, state) values ('Guaíra', 'PR');
insert into city (name, state) values ('Guamiranga', 'PR');
insert into city (name, state) values ('Ibiporã', 'PR');
insert into city (name, state) values ('Iguaraçu - PR', 'PR');
insert into city (name, state) values ('Iracema do Oeste', 'PR');
insert into city (name, state) values ('Itambé', 'PR');
insert into city (name, state) values ('Itapejara D´Oeste', 'PR');
insert into city (name, state) values ('IVAI PR', 'PR');
insert into city (name, state) values ('Ivaiporã', 'PR');
insert into city (name, state) values ('Ivatuba', 'PR');
insert into city (name, state) values ('JAGUAPITÃ', 'PR');
insert into city (name, state) values ('Jataizinho', 'PR');
insert into city (name, state) values ('Jussara PR', 'PR');
insert into city (name, state) values ('Kaloré-PR', 'PR');
insert into city (name, state) values ('Lobato', 'PR');
insert into city (name, state) values ('LONDRINA', 'PR');
insert into city (name, state) values ('Luiziana', 'PR');
insert into city (name, state) values ('Lupionópolis', 'PR');
insert into city (name, state) values ('Mal. Cândido Rondon', 'PR');
insert into city (name, state) values ('Mambore', 'PR');
insert into city (name, state) values ('Marechal Cândido Rondon', 'PR');
insert into city (name, state) values ('Marialva', 'PR');
insert into city (name, state) values ('Marilândia do Sul', 'PR');
insert into city (name, state) values ('Mariópolis PR', 'PR');
insert into city (name, state) values ('Marmeleiro - Pr', 'PR');
insert into city (name, state) values ('MERCEDES', 'PR');
insert into city (name, state) values ('Munhoz de Mello - PR', 'PR');
insert into city (name, state) values ('Nova Aurora PR', 'PR');
insert into city (name, state) values ('Nova Cantu', 'PR');
insert into city (name, state) values ('NOVA ESPERANCA DO SUDOESTE', 'PR');
insert into city (name, state) values ('Nova Laranjeiras', 'PR');
insert into city (name, state) values ('NOVA PRATA DO IGUAÇU', 'PR');
insert into city (name, state) values ('NOVA SANTA ROSA', 'PR');
insert into city (name, state) values ('NPI', 'PR');
insert into city (name, state) values ('Ourizona Pr', 'PR');
insert into city (name, state) values ('Ouro Verde do Oeste', 'PR');
insert into city (name, state) values ('Paiçandu Pr', 'PR');
insert into city (name, state) values ('PALOTINA - PR', 'PR');
insert into city (name, state) values ('Pato Branco', 'PR');
insert into city (name, state) values ('Pato Branco ', 'PR');
insert into city (name, state) values ('Paula Freitas', 'PR');
insert into city (name, state) values ('Paulo Frontin', 'PR');
insert into city (name, state) values ('Peabiru', 'PR');
insert into city (name, state) values ('PEABIRU PR', 'PR');
insert into city (name, state) values ('Pitanga – PR', 'PR');
insert into city (name, state) values ('Pitangueiras', 'PR');
insert into city (name, state) values ('Planalto', 'PR');
insert into city (name, state) values ('Ponta Grossa', 'PR');
insert into city (name, state) values ('Prado Ferreira', 'PR');
insert into city (name, state) values ('Pranchita PR', 'PR');
insert into city (name, state) values ('Primeiro de Maio -Pr', 'PR');
insert into city (name, state) values ('Quarto Centenário', 'PR');
insert into city (name, state) values ('QUATRO PONTES', 'PR');
insert into city (name, state) values ('Quedas do iguaçu', 'PR');
insert into city (name, state) values ('Quedas do Iguaçu Pr', 'PR');
insert into city (name, state) values ('Quinta do sol', 'PR');
insert into city (name, state) values ('Rancho Alegre DOeste', 'PR');
insert into city (name, state) values ('Realeza', 'PR');
insert into city (name, state) values ('RENASCENÇA PR', 'PR');
insert into city (name, state) values ('Reserva', 'PR');
insert into city (name, state) values ('Reserva do Iguaçu – Pr', 'PR');
insert into city (name, state) values ('Rio Azul', 'PR');
insert into city (name, state) values ('Rio Bonito do Iguaçu', 'PR');
insert into city (name, state) values ('Rolândia PR', 'PR');
insert into city (name, state) values ('Sabáudia-PR', 'PR');
insert into city (name, state) values ('Salto do Lontra', 'PR');
insert into city (name, state) values ('Santa Izabel do Oeste-PR', 'PR');
insert into city (name, state) values ('Santa Mariana', 'PR');
insert into city (name, state) values ('Santa Mariana', 'PR');
insert into city (name, state) values ('Santa Mariana ', 'PR');
insert into city (name, state) values ('São João do Triunfo', 'PR');
insert into city (name, state) values ('São João PR', 'PR');
insert into city (name, state) values ('SÃO JORGE D´OESTE PR', 'PR');
insert into city (name, state) values ('SÃO JORGE D´OESTE-PR', 'PR');
insert into city (name, state) values ('São Jorge do Ivaí - PR', 'PR');
insert into city (name, state) values ('São José das Palmeiras', 'PR');
insert into city (name, state) values ('SARANDI', 'PR');
insert into city (name, state) values ('Sengés', 'PR');
insert into city (name, state) values ('Sertaneja', 'PR');
insert into city (name, state) values ('Sertanópolis', 'PR');
insert into city (name, state) values ('Sta MarianaPr', 'PR');
insert into city (name, state) values ('Tamarana PR', 'PR');
insert into city (name, state) values ('Terra Roxa', 'PR');
insert into city (name, state) values ('Terra Roxa ', 'PR');
insert into city (name, state) values ('Tibagi', 'PR');
insert into city (name, state) values ('Toledo', 'PR');
insert into city (name, state) values ('TRÊS BARRAS DO PARANÁ', 'PR');
insert into city (name, state) values ('Tupãssi', 'PR');
insert into city (name, state) values ('Ubiratã', 'PR');
insert into city (name, state) values ('VERA CRUZ DO OESTE', 'PR');
insert into city (name, state) values ('Verê-PR', 'PR');
insert into city (name, state) values ('Vitorino Pr', 'PR');

insert into REGION_CITIES values (13, 1);
insert into REGION_CITIES values (5, 2);
insert into REGION_CITIES values (14, 3);
insert into REGION_CITIES values (1, 4);
insert into REGION_CITIES values (16, 5);
insert into REGION_CITIES values (6, 6);
insert into REGION_CITIES values (5, 7);
insert into REGION_CITIES values (18, 8);
insert into REGION_CITIES values (14, 9);
insert into REGION_CITIES values (17, 10);
insert into REGION_CITIES values (7, 11);
insert into REGION_CITIES values (8, 12);
insert into REGION_CITIES values (13, 13);
insert into REGION_CITIES values (19, 14);
insert into REGION_CITIES values (2, 15);
insert into REGION_CITIES values (3, 16);
insert into REGION_CITIES values (13, 17);
insert into REGION_CITIES values (17, 18);
insert into REGION_CITIES values (1, 19);
insert into REGION_CITIES values (2, 20);
insert into REGION_CITIES values (2, 21);
insert into REGION_CITIES values (11, 22);
insert into REGION_CITIES values (8, 23);
insert into REGION_CITIES values (3, 24);
insert into REGION_CITIES values (15, 25);
insert into REGION_CITIES values (15, 26);
insert into REGION_CITIES values (3, 27);
insert into REGION_CITIES values (5, 28);
insert into REGION_CITIES values (15, 29);
insert into REGION_CITIES values (7, 30);
insert into REGION_CITIES values (11, 31);
insert into REGION_CITIES values (7, 32);
insert into REGION_CITIES values (14, 33);
insert into REGION_CITIES values (8, 34);
insert into REGION_CITIES values (2, 35);
insert into REGION_CITIES values (18, 36);
insert into REGION_CITIES values (12, 37);
insert into REGION_CITIES values (2, 38);
insert into REGION_CITIES values (11, 39);
insert into REGION_CITIES values (14, 40);
insert into REGION_CITIES values (14, 41);
insert into REGION_CITIES values (13, 42);
insert into REGION_CITIES values (18, 43);
insert into REGION_CITIES values (8, 44);
insert into REGION_CITIES values (2, 45);
insert into REGION_CITIES values (9, 46);
insert into REGION_CITIES values (18, 47);
insert into REGION_CITIES values (10, 48);
insert into REGION_CITIES values (13, 49);
insert into REGION_CITIES values (14, 50);
insert into REGION_CITIES values (18, 51);
insert into REGION_CITIES values (14, 52);
insert into REGION_CITIES values (15, 53);
insert into REGION_CITIES values (16, 54);
insert into REGION_CITIES values (11, 55);
insert into REGION_CITIES values (14, 56);
insert into REGION_CITIES values (13, 57);
insert into REGION_CITIES values (5, 58);
insert into REGION_CITIES values (4, 59);
insert into REGION_CITIES values (1, 60);
insert into REGION_CITIES values (14, 61);
insert into REGION_CITIES values (13, 62);
insert into REGION_CITIES values (2, 63);
insert into REGION_CITIES values (13, 64);
insert into REGION_CITIES values (18, 65);
insert into REGION_CITIES values (2, 66);
insert into REGION_CITIES values (18, 67);
insert into REGION_CITIES values (14, 68);
insert into REGION_CITIES values (1, 69);
insert into REGION_CITIES values (15, 70);
insert into REGION_CITIES values (8, 71);
insert into REGION_CITIES values (18, 72);
insert into REGION_CITIES values (14, 73);
insert into REGION_CITIES values (3, 74);
insert into REGION_CITIES values (2, 75);
insert into REGION_CITIES values (7, 76);
insert into REGION_CITIES values (12, 77);
insert into REGION_CITIES values (7, 78);
insert into REGION_CITIES values (18, 79);
insert into REGION_CITIES values (7, 80);
insert into REGION_CITIES values (14, 81);
insert into REGION_CITIES values (18, 82);
insert into REGION_CITIES values (14, 83);
insert into REGION_CITIES values (18, 84);
insert into REGION_CITIES values (15, 85);
insert into REGION_CITIES values (15, 86);
insert into REGION_CITIES values (19, 87);
insert into REGION_CITIES values (19, 88);
insert into REGION_CITIES values (2, 89);
insert into REGION_CITIES values (2, 90);
insert into REGION_CITIES values (11, 91);
insert into REGION_CITIES values (13, 92);
insert into REGION_CITIES values (8, 93);
insert into REGION_CITIES values (16, 94);
insert into REGION_CITIES values (13, 95);
insert into REGION_CITIES values (8, 96);
insert into REGION_CITIES values (13, 97);
insert into REGION_CITIES values (2, 98);
insert into REGION_CITIES values (18, 99);
insert into REGION_CITIES values (12, 100);
insert into REGION_CITIES values (12, 101);
insert into REGION_CITIES values (2, 102);
insert into REGION_CITIES values (2, 103);
insert into REGION_CITIES values (8, 104);
insert into REGION_CITIES values (8, 105);
insert into REGION_CITIES values (16, 106);
insert into REGION_CITIES values (9, 107);
insert into REGION_CITIES values (10, 108);
insert into REGION_CITIES values (12, 109);
insert into REGION_CITIES values (13, 110);
insert into REGION_CITIES values (1, 111);
insert into REGION_CITIES values (7, 112);
insert into REGION_CITIES values (8, 113);
insert into REGION_CITIES values (5, 114);
insert into REGION_CITIES values (5, 115);
insert into REGION_CITIES values (5, 116);
insert into REGION_CITIES values (16, 117);
insert into REGION_CITIES values (15, 118);
insert into REGION_CITIES values (7, 119);
insert into REGION_CITIES values (7, 120);
insert into REGION_CITIES values (14, 121);
insert into REGION_CITIES values (18, 122);
insert into REGION_CITIES values (14, 123);
insert into REGION_CITIES values (16, 124);
insert into REGION_CITIES values (5, 125);
insert into REGION_CITIES values (13, 126);
insert into REGION_CITIES values (5, 127);
insert into REGION_CITIES values (13, 128);
insert into REGION_CITIES values (18, 129);
insert into REGION_CITIES values (18, 130);
insert into REGION_CITIES values (16, 131);
insert into REGION_CITIES values (18, 132);
insert into REGION_CITIES values (3, 133);
insert into REGION_CITIES values (18, 134);
insert into REGION_CITIES values (2, 135);
insert into REGION_CITIES values (3, 136);
insert into REGION_CITIES values (8, 137);
insert into REGION_CITIES values (15, 138);

insert into farmer (name) values ('Adão Dorigan');
insert into farmer (name) values ('Adelar José Machado');
insert into farmer (name) values ('Ademar Bald');
insert into farmer (name) values ('Ademar Hilario de Souza');
insert into farmer (name) values ('ADEMAR MIRANDA CONSTANTINO');
insert into farmer (name) values ('Ademilson Pegorini');
insert into farmer (name) values ('Ademir Rozada');
insert into farmer (name) values ('Adilson Antônio Fávero');
insert into farmer (name) values ('Adriano Mariani');
insert into farmer (name) values ('Agnaldo Rossato');
insert into farmer (name) values ('Alceu Vosniak');
insert into farmer (name) values ('Alci Fragoso da Costa');
insert into farmer (name) values ('Alcindo Alberton');
insert into farmer (name) values ('Altair Cazetta');
insert into farmer (name) values ('ALTAIR LINK');
insert into farmer (name) values ('ALTAIR ZANELLA');
insert into farmer (name) values ('Amadeu Segantim');
insert into farmer (name) values ('AMÉRICO PASQUARELLI');
insert into farmer (name) values ('André João de Azevedo');
insert into farmer (name) values ('Andrei Gamla');
insert into farmer (name) values ('Ângelo Calvi');
insert into farmer (name) values ('Anselmo J Bernadelli');
insert into farmer (name) values ('Antenor Janhaki');
insert into farmer (name) values ('Antonio Fabio Baroni');
insert into farmer (name) values ('Antonio Francisco Cava');
insert into farmer (name) values ('Antonio Giroto Sobrinho');
insert into farmer (name) values ('Antonio Marcos Waldrich');
insert into farmer (name) values ('Antônio Marioto');
insert into farmer (name) values ('Antonio Picoli Filho');
insert into farmer (name) values ('Antônio Roberto Pagotti');
insert into farmer (name) values ('Antonio Soares da Silva');
insert into farmer (name) values ('Antonio Targa Neto');
insert into farmer (name) values ('Antonio Wilson Zequin');
insert into farmer (name) values ('Armando Trampusch');
insert into farmer (name) values ('Augusto Voroniak');
insert into farmer (name) values ('BLEVIO MIGUEL');
insert into farmer (name) values ('Bruno Peralta');
insert into farmer (name) values ('Caetano José Rossi');
insert into farmer (name) values ('Caio Eduardo Dias');
insert into farmer (name) values ('Carlindo Baquião');
insert into farmer (name) values ('Carlo Saito');
insert into farmer (name) values ('Carlos Alberto Rampanelli');
insert into farmer (name) values ('Carlos José Tibério');
insert into farmer (name) values ('Carlos Pereira Alves');
insert into farmer (name) values ('Carlos Roberto Gomes Junior');
insert into farmer (name) values ('Celso Dalla Costa');
insert into farmer (name) values ('Centro Estadual Educação Profissional ');
insert into farmer (name) values ('Cicero dos Santos');
insert into farmer (name) values ('Claudecir José de Moura');
insert into farmer (name) values ('CLAUDENIR J. B. SEBRIAN');
insert into farmer (name) values ('Claudiner Ischida');
insert into farmer (name) values ('Claudino Candiotto');
insert into farmer (name) values ('Claudio Aparecido Alves');
insert into farmer (name) values ('Claudio Dalazem');
insert into farmer (name) values ('Claudiomar Thomazella');
insert into farmer (name) values ('Cleimar');
insert into farmer (name) values ('CLEMENTE CARNIELETTO');
insert into farmer (name) values ('CLETO CHADE');
insert into farmer (name) values ('Clovis de Barba');
insert into farmer (name) values ('Cristian Rodrigo Bidurin');
insert into farmer (name) values ('DANIEL PAULO DEIMLING');
insert into farmer (name) values ('Delber Antonio Novaes');
insert into farmer (name) values ('DENILSON RABER');
insert into farmer (name) values ('Diamantino Otelho Mariussi');
insert into farmer (name) values ('Domingos Verdi');
insert into farmer (name) values ('Dorivaldo Lourenço');
insert into farmer (name) values ('Eder Luis Burin');
insert into farmer (name) values ('EDGAR BUCHHOLZ');
insert into farmer (name) values ('Edio Luis Bitdinger');
insert into farmer (name) values ('Edivado Alves');
insert into farmer (name) values ('Edmar Gomes');
insert into farmer (name) values ('EDSON BOING');
insert into farmer (name) values ('Edson Contarin');
insert into farmer (name) values ('Edson de Oliveira');
insert into farmer (name) values ('Edson José Giongo');
insert into farmer (name) values ('Edson José Onning');
insert into farmer (name) values ('Edson Lindomar Draeger');
insert into farmer (name) values ('Edson Paulo Dalcultivo');
insert into farmer (name) values ('EDSON RICARDO REFATI');
insert into farmer (name) values ('Edson Rubbo');
insert into farmer (name) values ('Eduardo José Bolognse');
insert into farmer (name) values ('Eduardo Sudak');
insert into farmer (name) values ('Edvaldo Aparecido Gomes');
insert into farmer (name) values ('Edvaldo Cordeiro');
insert into farmer (name) values ('Elio Rosset');
insert into farmer (name) values ('Elizandro Lanfredi');
insert into farmer (name) values ('Eloi Pacifico da Silveira');
insert into farmer (name) values ('Emanuel Giotti');
insert into farmer (name) values ('Enio Luiz Alberton');
insert into farmer (name) values ('Eudiclei Copetti');
insert into farmer (name) values ('EVANDRO PIVETTA');
insert into farmer (name) values ('Everton M. Funghetto');
insert into farmer (name) values ('FABIO CARRARA');
insert into farmer (name) values ('Fábio Henrique Senci Aguiar');
insert into farmer (name) values ('Fabio Junior Junkes');
insert into farmer (name) values ('Fábio Von Gaevernitz Lima');
insert into farmer (name) values ('FACULDADE INTEGRADO');
insert into farmer (name) values ('Fernando Harka');
insert into farmer (name) values ('Francisco Benavides');
insert into farmer (name) values ('Geberson Alves de Souza');
insert into farmer (name) values ('Genilei Tritacci');
insert into farmer (name) values ('Gilson Dariva');
insert into farmer (name) values ('Gilson Duda');
insert into farmer (name) values ('Giovani Arantes Siqueira');
insert into farmer (name) values ('Helbner Marcelo Hebel');
insert into farmer (name) values ('Hermes Leandro Azeredo');
insert into farmer (name) values ('Humberto Antoniacomi');
insert into farmer (name) values ('Idair Molon');
insert into farmer (name) values ('Idalécio Bernardi');
insert into farmer (name) values ('Ildo Nunes Maciel');
insert into farmer (name) values ('Iliseu Berti');
insert into farmer (name) values ('Ilseu Peretti');
insert into farmer (name) values ('Ivan Boza');
insert into farmer (name) values ('IVAN COLTRO');
insert into farmer (name) values ('IVONEI BRUNO METZGER');
insert into farmer (name) values ('Jaime Geraldo Mantovani');
insert into farmer (name) values ('Jair da Rocha');
insert into farmer (name) values ('JAIR DE OLIVEIRA');
insert into farmer (name) values ('Jairo Baller');
insert into farmer (name) values ('JEAN CARLOS BORTOLOSO TRENTINI');
insert into farmer (name) values ('Jean Carlos Laconski do Carmo');
insert into farmer (name) values ('Jean Carlos Tonelli');
insert into farmer (name) values ('JEFERSON LUIZ HAMURA');
insert into farmer (name) values ('João Barba Conejo');
insert into farmer (name) values ('João Carlos Bichoffi');
insert into farmer (name) values ('João Carlos dos Santos');
insert into farmer (name) values ('João Claudemir Hartmann');
insert into farmer (name) values ('João Claudemir Mori');
insert into farmer (name) values ('João Correa Filho');
insert into farmer (name) values ('Joao Luis de Souza');
insert into farmer (name) values ('João Luiz Munhoz');
insert into farmer (name) values ('João Marcos de Melo');
insert into farmer (name) values ('JOÃO PEDRO BURILE');
insert into farmer (name) values ('JOÃO PEDRO VOLPATO');
insert into farmer (name) values ('Joaquim Monteiro Santana');
insert into farmer (name) values ('Jocemar Martinello');
insert into farmer (name) values ('John Maicon Machry');
insert into farmer (name) values ('José Calvi e José Bauli');
insert into farmer (name) values ('José Carlos Cunha');
insert into farmer (name) values ('Jose Carlos Neekel');
insert into farmer (name) values ('Jose Henrique');
insert into farmer (name) values ('Jose I. Steffens');
insert into farmer (name) values ('José Jarbas Fardin');
insert into farmer (name) values ('José Mansano');
insert into farmer (name) values ('Jose Nilson Leite ');
insert into farmer (name) values ('JOSE ODAIR H. MALANOTE');
insert into farmer (name) values ('José Pereira da Silva');
insert into farmer (name) values ('José Ribeiro');
insert into farmer (name) values ('José Roberto Scarparo');
insert into farmer (name) values ('JOSE SIDINEI LEANDRO');
insert into farmer (name) values ('Junior Vinicius de Lima Sangalli');
insert into farmer (name) values ('Juvencio Felismino Paiva');
insert into farmer (name) values ('Leoclinio Brufatti');
insert into farmer (name) values ('Leonardo Silveira ');
insert into farmer (name) values ('Lindomar Jose Massan');
insert into farmer (name) values ('Lino Luchtenberg');
insert into farmer (name) values ('LISNEY VENZON');
insert into farmer (name) values ('LUCIANO LUIZ ZORZI ALBERTON');
insert into farmer (name) values ('Luis Daniel Pasa');
insert into farmer (name) values ('Luis Gustavo Dalossi Guiciardi');
insert into farmer (name) values ('Luis Paulo Pasa');
insert into farmer (name) values ('Luis Sabo');
insert into farmer (name) values ('LUIS YOSHIUKI YAZAKI');
insert into farmer (name) values ('Luiz Bolonhesi');
insert into farmer (name) values ('Luiz Carlos  Bolognse');
insert into farmer (name) values ('Luiz Shigueru Higuchi');
insert into farmer (name) values ('Luiz Trevizolli');
insert into farmer (name) values ('Marcelo Antonio Bornia');
insert into farmer (name) values ('Marcelo Barbosa');
insert into farmer (name) values ('Márcio Bianchini');
insert into farmer (name) values ('Marcio Longo');
insert into farmer (name) values ('Marcio Ribeiro');
insert into farmer (name) values ('Marcos Fragal');
insert into farmer (name) values ('Marcos Franco Baeza');
insert into farmer (name) values ('Marlene Reisdorfer');
insert into farmer (name) values ('MATERDEI');
insert into farmer (name) values ('Maurilio Bertoldo');
insert into farmer (name) values ('MILTON KAZUTOSHI ITO');
insert into farmer (name) values ('NELSON DIAS');
insert into farmer (name) values ('Nelson Sambe ');
insert into farmer (name) values ('Neri da Silva');
insert into farmer (name) values ('Nerio Batista de Souza');
insert into farmer (name) values ('Nery Scheid');
insert into farmer (name) values ('Nilton Buzatto');
insert into farmer (name) values ('Nivaldo da Silva Lessa');
insert into farmer (name) values ('Nivaldo Spirandelli');
insert into farmer (name) values ('OLAVO EMILIO LOHMANN');
insert into farmer (name) values ('ORLANDO BEZ');
insert into farmer (name) values ('Oscar Riedo');
insert into farmer (name) values ('OSMAR WALTER FREITAS');
insert into farmer (name) values ('Osvaldecir Aparecido Balestri');
insert into farmer (name) values ('Osvaldir e Osvaldo  R. De Oliveira');
insert into farmer (name) values ('Paulino Francisco de Souza');
insert into farmer (name) values ('Paulo Caus Neto');
insert into farmer (name) values ('Paulo Israel Neto');
insert into farmer (name) values ('Paulo R. Fávaro');
insert into farmer (name) values ('PEDRO COELHO DO ROSARIO');
insert into farmer (name) values ('Rafael Vergani');
insert into farmer (name) values ('Reginaldo Ruthecoski Golon');
insert into farmer (name) values ('Ricardo Camara Silva');
insert into farmer (name) values ('Ricardo Chiyotti Massuda');
insert into farmer (name) values ('Ricardo Martim Bonatto');
insert into farmer (name) values ('ROBERTO BEDIN');
insert into farmer (name) values ('Roberto Bukowski');
insert into farmer (name) values ('Roberto Carlos Scarpin');
insert into farmer (name) values ('Rodolfo Ariza');
insert into farmer (name) values ('Rodolfo Prudente Marcolino');
insert into farmer (name) values ('Rogelio Pissoleti Salas');
insert into farmer (name) values ('Romildo Vasata');
insert into farmer (name) values ('Roni Marcarini');
insert into farmer (name) values ('Roque Deda e Silvestre Deda');
insert into farmer (name) values ('Sandro Rogério Tagliari');
insert into farmer (name) values ('Santo Mori');
insert into farmer (name) values ('Santo Pires Brito');
insert into farmer (name) values ('Selino Justino dos Santos ');
insert into farmer (name) values ('Sérgio Roberto da Silva');
insert into farmer (name) values ('SERGIO S IWASE');
insert into farmer (name) values ('SILVANO BATISTA MASERA');
insert into farmer (name) values ('Silvino Bueno Carneiro');
insert into farmer (name) values ('Silvino luiz Bosa');
insert into farmer (name) values ('Silvio Antonio Campanha');
insert into farmer (name) values ('Silvio Neto Pelizer');
insert into farmer (name) values ('Sueyoshi Tomizaki');
insert into farmer (name) values ('Takeu Yoshiy');
insert into farmer (name) values ('Valdemar Borgo');
insert into farmer (name) values ('Valdenir De Vechi');
insert into farmer (name) values ('Valdenir Torma Linhares');
insert into farmer (name) values ('Valderi Florentino da Silva');
insert into farmer (name) values ('VALDIR AGOSTINI');
insert into farmer (name) values ('Valdir Pelizer');
insert into farmer (name) values ('VALMOR DAL BELLO');
insert into farmer (name) values ('Valmor Sebben');
insert into farmer (name) values ('Valnil Tristão');
insert into farmer (name) values ('Valter Zanotti');
insert into farmer (name) values ('Vanderlei Turozi');
insert into farmer (name) values ('Vanderley Simões Montrean');
insert into farmer (name) values ('Vilson Mangini');
insert into farmer (name) values ('VINICIUS DARIEL BOCCHI');
insert into farmer (name) values ('WAGNER JOSÉ MARTENDAL DOS PASSOS');
insert into farmer (name) values ('Welton Jhon da Costa');

insert into SUPERVISOR (name, email, region_id) values ('ADEMILSON BRAVIM', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Afonso Faccin', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Agérico Anibal Carneiro Prestes', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('Alain C. Zola', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Alain Carmeiro Zola', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Alain Carneiro Zola', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('ALBERTO NERCI MULLER', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('ALEXANDRE BIANCHINI', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Anderson Luis Heling', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Antonio Carlos Rebeschini', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Antonio Carlos Rossin', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Antonio Eduardo Egydio', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Bernardo Faccin', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Bernardp Faccin', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Bruno Ribeiro Ananias', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Caio Quadros Netto', 'noone@gmail.com',1);
insert into SUPERVISOR (name, email, region_id) values ('Carlos Henrique Lelis', 'noone@gmail.com',1);
insert into SUPERVISOR (name, email, region_id) values ('Carlos Meleiro / João Vitor Carmezini', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Carlos Rodrigo Nunes de Oliveira', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Celestino Gabriel', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Celio Potrich', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Claiton Alorenus Baggio', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Claudemir luis Todescatt', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Claudinei A Minchio', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Claudio Holstein', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Cristiano Frigo', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Danilo Augusto Scharr', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('DIEGO S. PISSINATI', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Dinho Longaretti', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Diócles Castro e Silva', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('DIOGO MULLER', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Éden José Janisch', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('Edimilson Moreira', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Edson de Oliveira', 'noone@gmail.com',7);
insert into SUPERVISOR (name, email, region_id) values ('Eduardo Campos Barbosa', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Eduardo Mazzuchelli', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('EDUARDO VINICIUS STAFFEN WAMMES', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('EDUARDO WAMMES', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Edvaldo M. do Nascimento', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Elton R. Drebes', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Emerson Crivelaro Gomes', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('Emerson Gerstemberger', 'noone@gmail.com',8);
insert into SUPERVISOR (name, email, region_id) values ('Emerson Jopse Polonio', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('Emerson Jose Polonio', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('Emerson Jose Polonio', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('Enio Bragagnolo e Vanderlei Mariussi', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('ERISON ADRIANCZYK', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Everaldo Andrade De Ávila', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Everton Carlos R. de Souza', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Fabianderson J. B. de Souza/Ailton Rojas Poppi', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Fabianderson, Ailton Poppi', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Fabianderson/Ailton Poppi', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Fábio José Pires', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Fabrício Karas', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('Felipe Favoretto Furlan', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Felipe Machado de Freitas', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Fernanda Schubert M. Reis', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Fernando Borgert', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Fernando Ferreira da Silva', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Fernando Luis Martins Costa', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Gabriela Candido Weber', 'noone@gmail.com',7);
insert into SUPERVISOR (name, email, region_id) values ('Gerson schiochet', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('GILSON MARTINS', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('GLÁUCIA /NELSON', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Gláucia Dias Trevizan/Nelson R. B. Da Silva', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('GLAUCIA DIAS TREVIZAZN/ NELSON R. B. DA SILVA', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Gustavo M. de Oliveira', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Hemerson Bento Alves', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Hemerson Bento Alves.', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Ilvo Antoniazzi', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('Irani Castro da Silva Soares', 'noone@gmail.com',6);
insert into SUPERVISOR (name, email, region_id) values ('Ivan Domingos Freitas', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Ivanderson Borelli', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Jaci Fernandes de Souza', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('JAIR KLEIN', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Jayme Taube', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('João Carlos Taschetto', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('João Dozorec', 'noone@gmail.com',1);
insert into SUPERVISOR (name, email, region_id) values ('Joao Sergio Canterle', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Joel Rodrigues Fortes', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Joelson dos Santos', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Jonas Francisco Egewarth', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Jorge Luiz Rodrigues Valêncio', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Jorge Maurino da Silva', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('José Alberto de Mendonça', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('José Aloisio Basaglia', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('José Aparecido Baptista', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('JOSÉ V. JUAN', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Juvaldir Olimpio', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Karina Alves', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('Katerine E. Brero', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('LAERCIO MARCELO NASS', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('Lari Maroli', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Laura H G da Silva', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Laura Helena Goulart da Silva', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Leandro Jose Sperotto', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Leandro Michalovicz', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Luiz Carlos de Castro', 'noone@gmail.com',7);
insert into SUPERVISOR (name, email, region_id) values ('Luiz Henrique O. Souza', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Luiz Marcelo Franzin', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Luiz Pasquali', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Luiz Pedro Scatolin', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Luiza Tonelli', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Marcelo Vicensi', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('MARCIA CRISTINA LAWICH', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Marco Antonio da Silva Reis', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Marcos Antônio Bourscheid', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Marcos Antonio Paloschi', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Marcos Ludorf', 'noone@gmail.com',1);
insert into SUPERVISOR (name, email, region_id) values ('MATHEUS RIBEIRO', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Mauro Jair alves', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Melissa Berti', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('NELSON LUIZ KUNZLER', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('NELSON R. B. DA SILVA/ GLÁUCIA D. TREVIZAN', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Noel Justo de Oliveira', 'noone@gmail.com',16);
insert into SUPERVISOR (name, email, region_id) values ('ODIMAR DE MELLO', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Orestes Ramon Paladino', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('OSVALDO  MATYAK', 'noone@gmail.com',7);
insert into SUPERVISOR (name, email, region_id) values ('Pascoal Aparecido Palhares', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Paulo Cesa', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Paulo Eduardo Sipoli Pereira', 'noone@gmail.com',7);
insert into SUPERVISOR (name, email, region_id) values ('Paulo Roberto Mrtvi', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Paulo silva Barbosa', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Peter Alexandre v. Engelenhoven', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Rafael Alberto Guollo de Oliveira', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Reinaldo Neris dos Santos', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Renan Ribeiro Barzan', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Ricardo', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('Ricielly Eloyze Rosseto', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('ROBSON BRANDÃO', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('ROBSON FERREIRA FRANDAO', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Rodrigo Alexandre Patel da Fonseca', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('Romeu Gair', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Ronaldo Cesar Woyniak', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Sergio de Souza Lopes', 'noone@gmail.com',13);
insert into SUPERVISOR (name, email, region_id) values ('Sidney Carneiro/Valdemar Favreto', 'noone@gmail.com',18);
insert into SUPERVISOR (name, email, region_id) values ('Silvio C S Ferrari', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Silvio Cesar dos Santos Ferrari', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('Sinaney Delvan de Alencar Bozelli', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Urbano T. Mertz', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('VALDI BRISCHILIARI', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('VALDIR BRISCHILIARI', 'noone@gmail.com',19);
insert into SUPERVISOR (name, email, region_id) values ('VALDIR DASILVA', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Valdisio C Moreira', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Vanderlei Mariussi e Enio Bragagnolo', 'noone@gmail.com',17);
insert into SUPERVISOR (name, email, region_id) values ('VILMAR GRANDO', 'noone@gmail.com',2);
insert into SUPERVISOR (name, email, region_id) values ('Wagner Borghi', 'noone@gmail.com',5);
insert into SUPERVISOR (name, email, region_id) values ('Walber Hull da silva', 'noone@gmail.com',3);
insert into SUPERVISOR (name, email, region_id) values ('Willian Atanasio', 'noone@gmail.com',14);
insert into SUPERVISOR (name, email, region_id) values ('Zaqueu Cubines de Souza', 'noone@gmail.com',13);


INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Marcio Longo', 25, 171);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Ricardo Camara Silva', 26, 200);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Casa Pegorini', 53, 6);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'CARNIELETTO', 85, 57);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'MATERDEI', 85, 176);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Bertoldo', 86, 177);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Vasata', 85, 209);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Ilseu Peretti', 25, 112);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Trevo', 53, 102);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Coletor de esporos', 'Roni Marcarini', 70, 210);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('MT 1.062', 'Edson Onning', 53, 76);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Valdenir Torma Linhares', 70, 227);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Jocemar Martinello', 138, 136);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Jose I. Steffens', 25, 142);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Matriculas 5767', 'Lavoura', 138, 220);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Fernando Harka', 118, 98);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'João Claudemir Hartmann', 118, 127);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'ALTAIR ZANELLA', 29, 16);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'VINICIUS DARIEL BOCCHI', 29, 238);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Alcindo Alberton', 12, 13);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('06 PO /53', 'Edson José Giongo', 12, 75);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('02 PO/11', 'Enio Luiz Alberton', 12, 89);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Nery Scheid', 23, 183);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Elizandro Lanfredi', 34, 86);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('39/LR2', 'Leoclinio Brufatti', 44, 153);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('01 – NP – lote 29', 'Celso Dalla Costa', 71, 46);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Armando Trampusch', 93, 34);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Idair Molon', 93, 108);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('2º P.F.S.C., LR 17', 'Linha Tristacci', 96, 101);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Jair da Rocha', 104, 117);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('15-A – GL – BURITI MULATAS', 'JOÃO PEDRO BURILE', 105, 133);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('15-A – GL – Barra do Marmeleiro', 'LISNEY VENZON', 105, 157);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Sarandizinho', 113, 20);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Sarandi', 113, 92);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Carlos Alberto Rampanelli', 137, 42);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('379-D', 'MIP/COI/FER/GESTâo', 51, 189);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'ALTO ERVEIRA', 30, 188);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'ALTO ERVEIRA', 30, 72);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'BLEVIO MIGUEL', 80, 36);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'JOSE SIDINEI LEANDRO', 76, 150);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LR Nº 271 E 337 Gleba 06, Colonia Salmoura', 'PEDRO COELHO DO ROSARIO', 120, 197);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'André João de Azevedo', 32, 19);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LR Nº 80,Gleba 03, Colonia  Angico', 'VALDIR AGOSTINI', 119, 229);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'OSMAR WALTER FREITAS', 78, 190);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('68-FB', 'Clovis de Barba', 112, 59);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Domingos Verdi', 112, 65);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Idalécio Bernardi', 112, 109);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Marcio Ribeiro', 112, 172);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('25   56-FB', 'Claudino Candiotto', 11, 52);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'DENILSON RABER', 32, 63);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('L 36 e 37 GB 41 DV', 'Vilson Mangini', 32, 237);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'VALMOR DAL BELLO', 78, 231);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'MARTENDAL', 133, 239);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Iliseu Berti', 16, 111);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Ricardo Chiyotti Massuda', 16, 201);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'CLAUDENIR J. B. SEBRIAN', 136, 50);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'EDSON', 133, 79);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LR 18, GL 02', 'São Bento', 27, 88);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('79-A E 80-A-1', 'SÃO JOÃO', 74, 95);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('58-A-10, GL 02', 'Rancho Mundo', 27, 119);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('30-B', 'JOSE ODAIR H. MALANOTE', 136, 146);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'LUCIANO', 133, 158);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('GLEBA 10-B; LR 29-D', 'Luiz Trevizolli', 74, 167);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('44-B', 'NELSON DIAS', 136, 179);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'IVAN COLTRO', 136, 114);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'José Mansano', 1, 144);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Selino Justino dos Santos', 24, 215);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('05-A', 'SILVANO BATISTA MASERA', 136, 218);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('GL Silveiropolis/ LR 692-A, 692-B', 'Sim', 8, 152);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Zé Lulu/ Lote Rural 98-A', 'Sim', 8, 212);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('58,59-C', 'Sim', 8, 236);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'ERO 1', 36, 161);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'ERO Mip 2', 36, 159);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('418-A, 440', 'Mip, Gestão', 43, 130);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LR 118 4º Gleba', 'UR MIP e MID', 47, 85);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('53/B - 55/C', 'UR MID + MIP + GESTÃO', 65, 3);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('106.A.1', 'EDGAR BUCHHOLZ', 79, 68);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LR.55/A PER 13', 'LINHA SÃO JERONIMO', 99, 61);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'SJP 01', 122, 198);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'SPJ 2', 122, 234);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Claudio Dalazem', 129, 54);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('133-REM', 'Valnil Tristão', 130, 233);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('10-A Gleba Arnhold', 'Tupãssi_Carlos', 134, 44);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('51 Gleba Memória Colonia Pindorama', 'Diamantino', 134, 64);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'UR MID', 47, 195);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LR 32 Per 18º', 'Lino Luchtenberg', 67, 156);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('L . R. J -  6 DA G. J 38º PER', 'ALTAIR LINK', 72, 15);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('ROBERTO SEDE', 'APARECIDINHA', 84, 203);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'MID - SÃO LUIZ', 84, 91);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'MID - SÃO LUIZ', 84, 120);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'MID - PALMITAL', 84, 187);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sede', 'Sitio 3 do rio 3', 13, 126);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sede', 'Sitio São Francisco', 97, 191);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Claudecir José de Moura', 49, 49);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'João Correa Filho', 49, 129);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Paulo Caus Neto', 49, 194);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'FABIO CARRARA', 57, 93);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sede', 'Sitio 3 do rio 3', 13, 126);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sede', 'Sitio São Francisco', 97, 191);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Claudio Aparecido Alves', 62, 53);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Agnaldo Rossato', 126, 10);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'João Luiz Munhoz', 42, 131);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Lote 5-C Associação Cheiro da Terra', 'Dorivaldo Lourenço', 64, 66);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sítio Jesus Cristo é o Senhor', 'Carlos José Tibério', 64, 43);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Nivaldo Spirandelli', 62, 186);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Paulo R. Fávaro', 1, 196);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('25-A', 'Eduardo Sudak', 111, 82);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('CHACARA OURO VERDE', 'CAIO CAFEAR', 17, 39);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'João Marcos de Melo', 69, 132);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Amadeu Segantim', 60, 17);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Fábio Von Gaevernitz Lima', 19, 96);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('S Sao Francisco', 'Vanderlei Cafeara', 17, 235);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('S SAO PAULO', 'JAIR CAFEARA', 17, 118);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Paulino Francisco de Souza', 92, 193);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('235-M-7 e 235-M-5', 'IVONEI BRUNO METZGER', 15, 115);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Colégio Agrícola', 21, 47);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('GL 07; LT 218-A; 218-A-1 e 218-A-2', 'Sitio Agua da Fartura', 38, 204);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Lote 39-A-1', 'Geberson Alves de Souza', 63, 100);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Comunidade São Jorge', 75, 4);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'São Vicente', 89, 37);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'John Maicon Machry', 90, 137);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'FACULDADE INTEGRADO', 21, 97);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('XV', 'Sitio Monte das Oliveiras', 103, 124);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Comunidade São Jorge', 135, 222);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Ildo Nunes Maciel', 98, 110);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Matrícula 1.446', 135, 185);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Chác Baquião', 'MIP_2018/2019_Baquião', 20, 40);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LR 40A1F e 40A1G', 'MIP_2018/2019_Adilson', 20, 8);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Gleba Rio Mourão Lote 78-A, 76-A Matr. 8793,161', 'Sitio Santa Ines', 35, 87);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Gleba Rio Mourão', 'Chacara Eucalipto', 35, 77);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Luiz Carlos  Bolognse', 127, 165);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sitio Santo Antonio', 'Sitio Santo Antonio', 38, 67);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('sede', 'Família De Vechi', 45, 226);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Lote 12-R-1-', 'lote12-r-1', 63, 141);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('66-A', 'sim', 66, 225);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sitio Ouro Verde', 'Sede – Alto', 66, 32);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Sitio 3 Vendas', 102, 151);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('FRENTE', 'CLETO CHADE', 22, 58);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Jean Carlos Laconski do Carmo', 91, 121);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Antonio Marcos Waldrich', 4, 27);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Fábio Henrique Senci Aguiar', 10, 94);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Luis Gustavo Dalossi Guiciardi', 2, 160);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Sérgio Roberto da Silva', 7, 216);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Ivan Boza', 18, 113);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'José Roberto Scarparo', 18, 149);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Antônio Roberto Pagotti', 28, 30);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Rogelio Pissoleti Salas', 28, 208);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Valdir Pelizer', 58, 230);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Carlo Saito', 114, 41);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Edivado Alves', 114, 70);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Antonio Soares da Silva', 39, 31);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Vila Rural', 31, 62);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Severiano ', 'Leonardo Silveira ', 55, 154);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Edio Luis Bitdinger', 91, 69);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('72E/721Rem-A e 65 e 65-D-3', 'Francisco Benavides', 3, 99);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Márcio Bianchini', 3, 170);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('90-B', 'Nilton Buzatto', 3, 184);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Claudiner Ischida', 9, 51);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Cicero dos Santos', 50, 48);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Roberto Carlos Scarpin', 50, 205);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'JOÃO PEDRO VOLPATO', 123, 134);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Diversos', 'Santo Mori', 56, 213);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Est. N. S. Fátima', 'Alci Fragoso da Costa', 61, 12);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sítio Europa', 'Carlos Roberto Gomes Junior', 61, 45);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Fazenda Rechan 1', 'Claudiomar Thomazella', 61, 55);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sede', 'Edvaldo Cordeiro', 68, 84);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Gleba Ribeirão Aquidaban/Lote 81', 'João Carlos Bichoffi', 68, 125);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Dist. De Cambui', 'Marcos Fragal', 68, 173);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Bom Jessus Sede', 'Nerio Batista de Souza', 68, 182);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('88/89', 'Marcos Franco Baeza', 9, 174);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Caetano José Rossi', 40, 38);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('298 A-1-A', 'Valderi Florentino da Silva', 40, 228);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Rodolfo Prudente Marcolino', 50, 207);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('20 a 29', 'João Claudemir Mori', 56, 128);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('104/D', 'José Carlos Cunha', 56, 139);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Antonio Wilson Zequin', 73, 33);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Ângelo Calvi', 33, 21);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'José Calvi e José Bauli', 33, 138);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('99-A', 'Luis Sabo', 33, 162);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('616-B', 'Osvaldir e Osvaldo  R. De Oliveira', 33, 192);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LOTE 80 – GLEBA PINGUIM ', 'ADEMAR MIRANDA CONSTANTINO', 41, 5);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('LOTE 307-A – GLEBA PINGUIM ', 'AMÉRICO PASQUARELLI', 41, 18);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('296-A', 'LUIS YOSHIUKI YAZAKI', 41, 163);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('291-C; 292 DEST.; 292 REM.', 'MILTON KAZUTOSHI ITO', 41, 178);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Lote 81-C e 81-D', 'Antenor Janhaki', 52, 23);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('197 3-A/198-3', 'Sítio Uno', 52, 147);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Patrimônio Jussara, Lote 113', '02 – Giroto', 59, 26);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Patrimônio Jussara, Lotes 52a e 52b1', '01 – Geraldinho', 59, 116);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Ademir Rozada', 81, 7);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Patrimônio Jussara, Lote 14', '02 – Ribeiro', 59, 148);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Altair Cazetta', 81, 14);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Antonio Picoli Filho', 81, 29);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Adão Dorigan', 83, 1);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Antônio Marioto', 83, 28);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Luiz Bolonhesi', 83, 164);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Augusto Voroniak', 121, 35);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Edmar Gomes', 121, 71);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Cristian Rodrigo Bidurin', 121, 60);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Edvaldo Aparecido Gomes', 121, 83);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'José Jarbas Fardin', 121, 143);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Marcelo Barbosa', 121, 169);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Rodolfo Ariza', 127, 206);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Takeu Yoshiy', 125, 224);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Giovani Arantes Siqueira', 5, 104);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Soja', 'Lagoa', 117, 199);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Alceu Vosniak', 106, 11);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Mat 7763', 'JEFERSON LUIZ HAMURA', 54, 123);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Humberto Antoniacomi', 94, 107);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Silvino Bueno Carneiro', 131, 219);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Welton Jhon da Costa', 131, 240);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Eudiclei Copetti', 124, 90);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Joaquim Monteiro Santana', 128, 135);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'SERGIO S IWASE', 110, 217);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('lomba', 'Adriano Mariani', 48, 9);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Gilson Duda', 108, 103);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('lomba', 'Ricardo Martim Bonatto', 48, 202);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Sede', 'Sede', 87, 106);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Adelar José Machado', 14, 2);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Marlene Reisdorfer', 88, 175);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('casa', 'Edson Rubbo', 14, 80);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Valmor Sebben', 14, 232);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Antonio Francisco Cava', 107, 25);
INSERT INTO FIELD (LOCATION, NAME, CITY_ID, FARMER_ID) VALUES ('Não definida', 'Silvio Antonio Campanha', 46, 221);


INSERT INTO FIELD_SUPERVISORS VALUES (1, 101);
INSERT INTO FIELD_SUPERVISORS VALUES (2, 106);
INSERT INTO FIELD_SUPERVISORS VALUES (3, 93);
INSERT INTO FIELD_SUPERVISORS VALUES (4, 146);
INSERT INTO FIELD_SUPERVISORS VALUES (5, 146);
INSERT INTO FIELD_SUPERVISORS VALUES (6, 67);
INSERT INTO FIELD_SUPERVISORS VALUES (7, 67);
INSERT INTO FIELD_SUPERVISORS VALUES (8, 101);
INSERT INTO FIELD_SUPERVISORS VALUES (9, 93);
INSERT INTO FIELD_SUPERVISORS VALUES (10, 73);
INSERT INTO FIELD_SUPERVISORS VALUES (11, 26);
INSERT INTO FIELD_SUPERVISORS VALUES (12, 73);
INSERT INTO FIELD_SUPERVISORS VALUES (13, 62);
INSERT INTO FIELD_SUPERVISORS VALUES (14, 101);
INSERT INTO FIELD_SUPERVISORS VALUES (15, 62);
INSERT INTO FIELD_SUPERVISORS VALUES (16, 134);
INSERT INTO FIELD_SUPERVISORS VALUES (17, 134);
INSERT INTO FIELD_SUPERVISORS VALUES (18, 116);
INSERT INTO FIELD_SUPERVISORS VALUES (19, 116);
INSERT INTO FIELD_SUPERVISORS VALUES (20, 81);
INSERT INTO FIELD_SUPERVISORS VALUES (21, 81);
INSERT INTO FIELD_SUPERVISORS VALUES (22, 81);
INSERT INTO FIELD_SUPERVISORS VALUES (23, 40);
INSERT INTO FIELD_SUPERVISORS VALUES (24, 125);
INSERT INTO FIELD_SUPERVISORS VALUES (25, 79);
INSERT INTO FIELD_SUPERVISORS VALUES (26, 108);
INSERT INTO FIELD_SUPERVISORS VALUES (27, 103);
INSERT INTO FIELD_SUPERVISORS VALUES (28, 25);
INSERT INTO FIELD_SUPERVISORS VALUES (29, 136);
INSERT INTO FIELD_SUPERVISORS VALUES (30, 76);
INSERT INTO FIELD_SUPERVISORS VALUES (31, 7);
INSERT INTO FIELD_SUPERVISORS VALUES (32, 7);
INSERT INTO FIELD_SUPERVISORS VALUES (33, 29);
INSERT INTO FIELD_SUPERVISORS VALUES (34, 29);
INSERT INTO FIELD_SUPERVISORS VALUES (35, 102);
INSERT INTO FIELD_SUPERVISORS VALUES (36, 23);
INSERT INTO FIELD_SUPERVISORS VALUES (37, 8);
INSERT INTO FIELD_SUPERVISORS VALUES (38, 8);
INSERT INTO FIELD_SUPERVISORS VALUES (39, 130);
INSERT INTO FIELD_SUPERVISORS VALUES (40, 110);
INSERT INTO FIELD_SUPERVISORS VALUES (41, 75);
INSERT INTO FIELD_SUPERVISORS VALUES (42, 107);
INSERT INTO FIELD_SUPERVISORS VALUES (43, 75);
INSERT INTO FIELD_SUPERVISORS VALUES (44, 131);
INSERT INTO FIELD_SUPERVISORS VALUES (45, 104);
INSERT INTO FIELD_SUPERVISORS VALUES (46, 104);
INSERT INTO FIELD_SUPERVISORS VALUES (47, 104);
INSERT INTO FIELD_SUPERVISORS VALUES (48, 104);
INSERT INTO FIELD_SUPERVISORS VALUES (49, 144);
INSERT INTO FIELD_SUPERVISORS VALUES (50, 143);
INSERT INTO FIELD_SUPERVISORS VALUES (51, 143);
INSERT INTO FIELD_SUPERVISORS VALUES (52, 131);
INSERT INTO FIELD_SUPERVISORS VALUES (53, 31);
INSERT INTO FIELD_SUPERVISORS VALUES (54, 129);
INSERT INTO FIELD_SUPERVISORS VALUES (55, 129);
INSERT INTO FIELD_SUPERVISORS VALUES (56, 114);
INSERT INTO FIELD_SUPERVISORS VALUES (57, 31);
INSERT INTO FIELD_SUPERVISORS VALUES (58, 149);
INSERT INTO FIELD_SUPERVISORS VALUES (59, 58);
INSERT INTO FIELD_SUPERVISORS VALUES (60, 149);
INSERT INTO FIELD_SUPERVISORS VALUES (61, 66);
INSERT INTO FIELD_SUPERVISORS VALUES (62, 31);
INSERT INTO FIELD_SUPERVISORS VALUES (63, 58);
INSERT INTO FIELD_SUPERVISORS VALUES (64, 65);
INSERT INTO FIELD_SUPERVISORS VALUES (65, 64);
INSERT INTO FIELD_SUPERVISORS VALUES (66, 126);
INSERT INTO FIELD_SUPERVISORS VALUES (67, 30);
INSERT INTO FIELD_SUPERVISORS VALUES (68, 66);
INSERT INTO FIELD_SUPERVISORS VALUES (69, 77);
INSERT INTO FIELD_SUPERVISORS VALUES (70, 132);
INSERT INTO FIELD_SUPERVISORS VALUES (71, 77);
INSERT INTO FIELD_SUPERVISORS VALUES (72, 82);
INSERT INTO FIELD_SUPERVISORS VALUES (73, 82);
INSERT INTO FIELD_SUPERVISORS VALUES (74, 39);
INSERT INTO FIELD_SUPERVISORS VALUES (75, 2);
INSERT INTO FIELD_SUPERVISORS VALUES (76, 140);
INSERT INTO FIELD_SUPERVISORS VALUES (77, 88);
INSERT INTO FIELD_SUPERVISORS VALUES (78, 113);
INSERT INTO FIELD_SUPERVISORS VALUES (79, 9);
INSERT INTO FIELD_SUPERVISORS VALUES (80, 9);
INSERT INTO FIELD_SUPERVISORS VALUES (81, 14);
INSERT INTO FIELD_SUPERVISORS VALUES (82, 13);
INSERT INTO FIELD_SUPERVISORS VALUES (83, 46);
INSERT INTO FIELD_SUPERVISORS VALUES (84, 145);
INSERT INTO FIELD_SUPERVISORS VALUES (85, 2);
INSERT INTO FIELD_SUPERVISORS VALUES (86, 20);
INSERT INTO FIELD_SUPERVISORS VALUES (87, 105);
INSERT INTO FIELD_SUPERVISORS VALUES (88, 37);
INSERT INTO FIELD_SUPERVISORS VALUES (89, 38);
INSERT INTO FIELD_SUPERVISORS VALUES (90, 38);
INSERT INTO FIELD_SUPERVISORS VALUES (91, 38);
INSERT INTO FIELD_SUPERVISORS VALUES (92, 89);
INSERT INTO FIELD_SUPERVISORS VALUES (93, 89);
INSERT INTO FIELD_SUPERVISORS VALUES (94, 127);
INSERT INTO FIELD_SUPERVISORS VALUES (95, 127);
INSERT INTO FIELD_SUPERVISORS VALUES (96, 127);
INSERT INTO FIELD_SUPERVISORS VALUES (97, 28);
INSERT INTO FIELD_SUPERVISORS VALUES (98, 89);
INSERT INTO FIELD_SUPERVISORS VALUES (99, 89);
INSERT INTO FIELD_SUPERVISORS VALUES (100, 122);
INSERT INTO FIELD_SUPERVISORS VALUES (101, 111);
INSERT INTO FIELD_SUPERVISORS VALUES (102, 60);
INSERT INTO FIELD_SUPERVISORS VALUES (103, 19);
INSERT INTO FIELD_SUPERVISORS VALUES (104, 19);
INSERT INTO FIELD_SUPERVISORS VALUES (105, 133);
INSERT INTO FIELD_SUPERVISORS VALUES (106, 126);
INSERT INTO FIELD_SUPERVISORS VALUES (107, 100);
INSERT INTO FIELD_SUPERVISORS VALUES (108, 10);
INSERT INTO FIELD_SUPERVISORS VALUES (109, 56);
INSERT INTO FIELD_SUPERVISORS VALUES (110, 150);
INSERT INTO FIELD_SUPERVISORS VALUES (111, 124);
INSERT INTO FIELD_SUPERVISORS VALUES (112, 10);
INSERT INTO FIELD_SUPERVISORS VALUES (113, 10);
INSERT INTO FIELD_SUPERVISORS VALUES (114, 55);
INSERT INTO FIELD_SUPERVISORS VALUES (115, 63);
INSERT INTO FIELD_SUPERVISORS VALUES (116, 147);
INSERT INTO FIELD_SUPERVISORS VALUES (117, 35);
INSERT INTO FIELD_SUPERVISORS VALUES (118, 95);
INSERT INTO FIELD_SUPERVISORS VALUES (119, 99);
INSERT INTO FIELD_SUPERVISORS VALUES (120, 12);
INSERT INTO FIELD_SUPERVISORS VALUES (121, 84);
INSERT INTO FIELD_SUPERVISORS VALUES (122, 12);
INSERT INTO FIELD_SUPERVISORS VALUES (123, 123);
INSERT INTO FIELD_SUPERVISORS VALUES (124, 68);
INSERT INTO FIELD_SUPERVISORS VALUES (125, 86);
INSERT INTO FIELD_SUPERVISORS VALUES (126, 69);
INSERT INTO FIELD_SUPERVISORS VALUES (127, 48);
INSERT INTO FIELD_SUPERVISORS VALUES (128, 48);
INSERT INTO FIELD_SUPERVISORS VALUES (129, 139);
INSERT INTO FIELD_SUPERVISORS VALUES (130, 139);
INSERT INTO FIELD_SUPERVISORS VALUES (131, 74);
INSERT INTO FIELD_SUPERVISORS VALUES (132, 35);
INSERT INTO FIELD_SUPERVISORS VALUES (133, 49);
INSERT INTO FIELD_SUPERVISORS VALUES (134, 94);
INSERT INTO FIELD_SUPERVISORS VALUES (135, 120);
INSERT INTO FIELD_SUPERVISORS VALUES (136, 120);
INSERT INTO FIELD_SUPERVISORS VALUES (137, 15);
INSERT INTO FIELD_SUPERVISORS VALUES (138, 118);
INSERT INTO FIELD_SUPERVISORS VALUES (139, 61);
INSERT INTO FIELD_SUPERVISORS VALUES (140, 124);
INSERT INTO FIELD_SUPERVISORS VALUES (141, 53);
INSERT INTO FIELD_SUPERVISORS VALUES (142, 90);
INSERT INTO FIELD_SUPERVISORS VALUES (143, 41);
INSERT INTO FIELD_SUPERVISORS VALUES (144, 11);
INSERT INTO FIELD_SUPERVISORS VALUES (145, 11);
INSERT INTO FIELD_SUPERVISORS VALUES (146, 115);
INSERT INTO FIELD_SUPERVISORS VALUES (147, 115);
INSERT INTO FIELD_SUPERVISORS VALUES (148, 87);
INSERT INTO FIELD_SUPERVISORS VALUES (149, 44);
INSERT INTO FIELD_SUPERVISORS VALUES (150, 44);
INSERT INTO FIELD_SUPERVISORS VALUES (151, 98);
INSERT INTO FIELD_SUPERVISORS VALUES (152, 121);
INSERT INTO FIELD_SUPERVISORS VALUES (153, 34);
INSERT INTO FIELD_SUPERVISORS VALUES (154, 61);
INSERT INTO FIELD_SUPERVISORS VALUES (155, 33);
INSERT INTO FIELD_SUPERVISORS VALUES (156, 33);
INSERT INTO FIELD_SUPERVISORS VALUES (157, 33);
INSERT INTO FIELD_SUPERVISORS VALUES (158, 80);
INSERT INTO FIELD_SUPERVISORS VALUES (159, 59);
INSERT INTO FIELD_SUPERVISORS VALUES (160, 59);
INSERT INTO FIELD_SUPERVISORS VALUES (161, 1);
INSERT INTO FIELD_SUPERVISORS VALUES (162, 5);
INSERT INTO FIELD_SUPERVISORS VALUES (163, 119);
INSERT INTO FIELD_SUPERVISORS VALUES (164, 119);
INSERT INTO FIELD_SUPERVISORS VALUES (165, 119);
INSERT INTO FIELD_SUPERVISORS VALUES (166, 51);
INSERT INTO FIELD_SUPERVISORS VALUES (167, 52);
INSERT INTO FIELD_SUPERVISORS VALUES (168, 52);
INSERT INTO FIELD_SUPERVISORS VALUES (169, 50);
INSERT INTO FIELD_SUPERVISORS VALUES (170, 80);
INSERT INTO FIELD_SUPERVISORS VALUES (171, 83);
INSERT INTO FIELD_SUPERVISORS VALUES (172, 83);
INSERT INTO FIELD_SUPERVISORS VALUES (173, 59);
INSERT INTO FIELD_SUPERVISORS VALUES (174, 4);
INSERT INTO FIELD_SUPERVISORS VALUES (175, 6);
INSERT INTO FIELD_SUPERVISORS VALUES (176, 59);
INSERT INTO FIELD_SUPERVISORS VALUES (177, 85);
INSERT INTO FIELD_SUPERVISORS VALUES (178, 138);
INSERT INTO FIELD_SUPERVISORS VALUES (179, 137);
INSERT INTO FIELD_SUPERVISORS VALUES (180, 85);
INSERT INTO FIELD_SUPERVISORS VALUES (181, 142);
INSERT INTO FIELD_SUPERVISORS VALUES (182, 142);
INSERT INTO FIELD_SUPERVISORS VALUES (183, 141);
INSERT INTO FIELD_SUPERVISORS VALUES (184, 141);
INSERT INTO FIELD_SUPERVISORS VALUES (185, 72);
INSERT INTO FIELD_SUPERVISORS VALUES (186, 72);
INSERT INTO FIELD_SUPERVISORS VALUES (187, 17);
INSERT INTO FIELD_SUPERVISORS VALUES (188, 17);
INSERT INTO FIELD_SUPERVISORS VALUES (189, 57);
INSERT INTO FIELD_SUPERVISORS VALUES (190, 17);
INSERT INTO FIELD_SUPERVISORS VALUES (191, 57);
INSERT INTO FIELD_SUPERVISORS VALUES (192, 57);
INSERT INTO FIELD_SUPERVISORS VALUES (193, 91);
INSERT INTO FIELD_SUPERVISORS VALUES (194, 91);
INSERT INTO FIELD_SUPERVISORS VALUES (195, 91);
INSERT INTO FIELD_SUPERVISORS VALUES (196, 36);
INSERT INTO FIELD_SUPERVISORS VALUES (197, 36);
INSERT INTO FIELD_SUPERVISORS VALUES (198, 24);
INSERT INTO FIELD_SUPERVISORS VALUES (199, 36);
INSERT INTO FIELD_SUPERVISORS VALUES (200, 24);
INSERT INTO FIELD_SUPERVISORS VALUES (201, 24);
INSERT INTO FIELD_SUPERVISORS VALUES (202, 74);
INSERT INTO FIELD_SUPERVISORS VALUES (203, 70);
INSERT INTO FIELD_SUPERVISORS VALUES (204, 27);
INSERT INTO FIELD_SUPERVISORS VALUES (205, 54);
INSERT INTO FIELD_SUPERVISORS VALUES (206, 112);
INSERT INTO FIELD_SUPERVISORS VALUES (207, 92);
INSERT INTO FIELD_SUPERVISORS VALUES (208, 32);
INSERT INTO FIELD_SUPERVISORS VALUES (209, 3);
INSERT INTO FIELD_SUPERVISORS VALUES (210, 148);
INSERT INTO FIELD_SUPERVISORS VALUES (211, 128);
INSERT INTO FIELD_SUPERVISORS VALUES (212, 18);
INSERT INTO FIELD_SUPERVISORS VALUES (213, 28);
INSERT INTO FIELD_SUPERVISORS VALUES (214, 96);
INSERT INTO FIELD_SUPERVISORS VALUES (215, 47);
INSERT INTO FIELD_SUPERVISORS VALUES (216, 117);
INSERT INTO FIELD_SUPERVISORS VALUES (217, 78);
INSERT INTO FIELD_SUPERVISORS VALUES (218, 16);
INSERT INTO FIELD_SUPERVISORS VALUES (219, 109);
INSERT INTO FIELD_SUPERVISORS VALUES (220, 16);
INSERT INTO FIELD_SUPERVISORS VALUES (221, 16);
INSERT INTO FIELD_SUPERVISORS VALUES (222, 97);
INSERT INTO FIELD_SUPERVISORS VALUES (223, 22);

INSERT INTO HARVEST (BEGIN, END, NAME) VALUES ('2018-10-01', '2019-03-31', 'Safra 2018/2019');
INSERT INTO HARVEST (BEGIN, END, NAME) VALUES ('2019-10-01', '2020-03-31', 'Safra 2019/2020');

INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MENOR_15CM', 'Anticarsia', 'Lagarta-da- soja');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MAIOR_15CM', 'Anticarsia', 'Lagarta-da- soja');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MENOR_15CM', 'Chrysodeixis', 'Lagarta-falsa-medideira');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MAIOR_15CM', 'Chrysodeixis', 'Lagarta-falsa-medideira');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MENOR_15CM', 'Spodoptera spp.', 'Lagarta-das-vagens');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MAIOR_15CM', 'Spodoptera spp.', 'Lagarta-das-vagens');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MENOR_15CM', '', 'Lagartas do grupo Heliothinae');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('MAIOR_15CM', '', 'Lagartas do grupo Heliothinae');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('TERCEIRO_AO_QUINTO_INSTAR', 'Nezara', 'Percevejo-verde');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', 'Nezara', 'Percevejo-verde');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('TERCEIRO_AO_QUINTO_INSTAR', 'Piezodorus', 'Percevejo-pequeno');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', 'Piezodorus', 'Percevejo-pequeno');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('TERCEIRO_AO_QUINTO_INSTAR', 'Euschistus', 'Percevejo-marrom');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', 'Euschistus', 'Percevejo-marrom');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('TERCEIRO_AO_QUINTO_INSTAR', 'Dichelops', 'Percevejo-barriga-verde');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', 'Dichelops', 'Percevejo-barriga-verde');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('TERCEIRO_AO_QUINTO_INSTAR', '', 'Outros percevejos');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', '', 'Outros percevejos');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('PONTEIROS_ATACADOS', 'Crocidosema', 'Broca-dos-ponteiros');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', 'Sternechus', 'Tamanduá-da-soja');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', 'Diabrotica-Cerotoma-Colaspis', 'Vaquinhas');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('ADULTO', 'Aracanthus', 'Torrãozinho');
INSERT INTO PEST (PEST_SIZE, SCIENTIFIC_NAME, USUAL_NAME) VALUES ('OUTRO', '', 'Outros insetos');

INSERT INTO PEST_DISEASE (USUAL_NAME) VALUES ('Lagarta com Nomuraea (doença branca)');
INSERT INTO PEST_DISEASE (USUAL_NAME) VALUES ('Lagarta com Baculovirus (doença preta)');

INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Calosoma granulatum');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Callida sp.');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Callida scutellaris');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Lebia concinna');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Eriopsis connexa');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Cycloneda sanguinea');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Podisus sp.');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Tropiconabis sp.');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Geocoris sp.');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Doru sp. (tesourinha)');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Aranhas');
INSERT INTO PEST_NATURAL_PREDATOR (USUAL_NAME) VALUES ('Outros');

INSERT INTO PRODUCT (NAME, USE_CLASS, UNIT, CONCENTRATION_ACTIVE_INGREDIENT, REGISTER_NUMBER, COMPANY, TOXI_CLASS, ACTIVE_INGREDIENT) VALUES ('2,4 D (240) + PICLORAM (64) SL', 'HERBICIDA', 'L', '406 + 103,6', 31918, 'CCAB', 'I', '2,4 D + PICLORAM');
